//! Model download with resume support using reqwest.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use tokio::io::AsyncWriteExt;

pub struct CatalogModel {
    pub name: &'static str,
    pub file: &'static str,
    pub url: &'static str,
    pub size: &'static str,
    pub description: &'static str,
    /// If set, this model has a recommended draft model for speculative decoding.
    pub draft: Option<&'static str>,
    /// MoE expert routing config. If set, this model supports expert sharding.
    /// Pre-computed from `moe-analyze --export-ranking --all-layers`.
    pub moe: Option<MoeConfig>,
    /// Additional split GGUF files (for models too large for a single file).
    /// Each entry is (filename, url). llama.cpp auto-discovers splits from the
    /// first file, but all parts must be present in the same directory.
    pub extra_files: &'static [(&'static str, &'static str)],
}

/// Pre-computed MoE expert sharding configuration for a model.
/// Derived from router gate mass analysis — determines which experts go where.
#[derive(Clone, Debug)]
pub struct MoeConfig {
    /// Total number of experts in the model
    pub n_expert: u32,
    /// Number of experts selected per token (top-k)
    pub n_expert_used: u32,
    /// Minimum number of experts per node for coherent output.
    /// Determined experimentally per model (~36% for Qwen3-30B-A3B).
    pub min_experts_per_node: u32,
    /// Expert IDs sorted by gate mass descending (hottest first).
    /// This is the content of the ranking CSV, embedded directly.
    pub ranking: &'static [u32],

}

// Pre-computed expert rankings by gate mass (hottest first).
// Generated by: llama-moe-analyze --export-ranking --all-layers
// These are a property of the model weights — compute once, embed forever.

#[rustfmt::skip]
static QWEN3_30B_A3B_RANKING: &[u32] = &[
    0, 26, 41, 69, 104, 70, 81, 89, 7, 21, 105, 75, 8, 78, 82, 5, 115, 16, 59, 32,
    111, 38, 103, 49, 51, 73, 96, 85, 18, 71, 68, 2, 47, 37, 58, 24, 110, 57, 65, 98,
    14, 80, 52, 112, 113, 36, 84, 9, 30, 28, 66, 122, 50, 92, 1, 10, 3, 91, 56, 117,
    87, 17, 64, 34, 25, 94, 33, 86, 102, 74, 120, 31, 4, 45, 13, 61, 99, 93, 107, 46,
    48, 55, 35, 12, 22, 124, 29, 27, 53, 44, 6, 39, 123, 116, 101, 126, 62, 127, 106, 97,
    63, 72, 109, 42, 125, 20, 76, 43, 121, 90, 100, 77, 23, 119, 83, 11, 54, 19, 114, 79,
    108, 40, 67, 88, 60, 95, 118, 15,
];

pub const MODEL_CATALOG: &[CatalogModel] = &[
    // ── Tiny (≤3GB VRAM) ────────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-4B-Q4_K_M",
        file: "Qwen3-4B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
        size: "2.5GB",
        description: "Qwen3 starter, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-3B-Instruct-Q4_K_M",
        file: "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
        size: "2.1GB",
        description: "Small & fast general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Llama-3.2-3B-Instruct-Q4_K_M",
        file: "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        size: "2.0GB",
        description: "Meta Llama 3.2, goose default, good tool calling",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    // ── Small (6-8GB VRAM) ──────────────────────────────────────────
    CatalogModel {
        name: "Qwen3-8B-Q4_K_M",
        file: "Qwen3-8B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf",
        size: "5.0GB",
        description: "Qwen3 mid-tier, strong for its size",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-Coder-7B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf",
        size: "4.4GB",
        description: "Code generation & completion",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Gemma-3-12B-it-Q4_K_M",
        file: "Gemma-3-12B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf",
        size: "7.3GB",
        description: "Google Gemma 3 12B, punches above weight",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Hermes-2-Pro-Mistral-7B-Q4_K_M",
        file: "Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Hermes-2-Pro-Mistral-7B-GGUF/resolve/main/Hermes-2-Pro-Mistral-7B-Q4_K_M.gguf",
        size: "4.4GB",
        description: "Goose default, strong tool calling for agents",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    // ── Medium (11-17GB VRAM) ───────────────────────────────────────
    CatalogModel {
        name: "Qwen3-14B-Q4_K_M",
        file: "Qwen3-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Qwen3 strong chat, thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Solid general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-Coder-14B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-Coder-14B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf",
        size: "9.0GB",
        description: "Strong code gen, fills gap between 7B and 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf",
        size: "9.0GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 14B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Devstral-Small-2505-Q4_K_M",
        file: "Devstral-Small-2505-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Devstral-Small-2505-GGUF/resolve/main/Devstral-Small-2505-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral agentic coding, tool use",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Mistral-Small-3.1-24B-Instruct-Q4_K_M",
        file: "Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf",
        size: "14.3GB",
        description: "Mistral general chat, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    // ── Large (20-24GB VRAM) ────────────────────────────────────────
    CatalogModel {
        name: "GLM-4.7-Flash-Q4_K_M",
        file: "GLM-4.7-Flash-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF/resolve/main/GLM-4.7-Flash-Q4_K_M.gguf",
        size: "18GB",
        description: "MoE 30B/3B active, 64 experts top-4, fast inference, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 64,
            n_expert_used: 4,
            min_experts_per_node: 24,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect + fallback
        }),
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen3-30B-A3B-Q4_K_M",
        file: "Qwen3-30B-A3B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-30B-A3B-GGUF/resolve/main/Qwen3-30B-A3B-Q4_K_M.gguf",
        size: "17.3GB",
        description: "MoE general chat, 128 experts top-8, thinking/non-thinking",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Coder variant
        }),
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M",
        file: "Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        size: "18.6GB",
        description: "MoE agentic coding, tool use, 128 experts top-8",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: Some(MoeConfig {
            n_expert: 128,
            n_expert_used: 8,
            min_experts_per_node: 46,
            ranking: QWEN3_30B_A3B_RANKING, // same arch as Qwen3-30B-A3B
        }),
        extra_files: &[],
    },
    CatalogModel {
        name: "GLM-4-32B-0414-Q4_K_M",
        file: "GLM-4-32B-0414-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/GLM-4-32B-0414-GGUF/resolve/main/GLM-4-32B-0414-Q4_K_M.gguf",
        size: "19.7GB",
        description: "Strong 32B, good tool calling",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen3-32B-Q4_K_M",
        file: "Qwen3-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-32B-GGUF/resolve/main/Qwen3-32B-Q4_K_M.gguf",
        size: "19.8GB",
        description: "Best Qwen3 dense, thinking/non-thinking modes",
        draft: Some("Qwen3-0.6B-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M",
        file: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
        size: "19.9GB",
        description: "DeepSeek R1 reasoning distilled into Qwen 32B",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        size: "20GB",
        description: "Proven general chat",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-Coder-32B-Instruct-Q4_K_M",
        file: "Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/qwen2.5-coder-32b-instruct-q4_k_m.gguf",
        size: "20GB",
        description: "Top-tier code gen, matches GPT-4o on code",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Llama-4-Scout-Q4_K_M",
        file: "Llama-4-Scout-4bit-Q4_K_M.gguf",
        url: "https://huggingface.co/glogwa68/Llama-4-scout-GGUF/resolve/main/Llama-4-Scout-4bit-Q4_K_M.gguf",
        size: "22.5GB",
        description: "MoE 109B/17B active, 16 experts top-1, Meta latest, tool calling",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 16,
            n_expert_used: 1,
            min_experts_per_node: 6,
            ranking: &[], // no pre-baked ranking — uses GGUF auto-detect
        }),
        extra_files: &[],
    },
    CatalogModel {
        name: "Gemma-3-27B-it-Q4_K_M",
        file: "Gemma-3-27B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-27b-it-GGUF/resolve/main/google_gemma-3-27b-it-Q4_K_M.gguf",
        size: "17GB",
        description: "Google Gemma 3 27B, strong reasoning",
        draft: Some("Gemma-3-1B-it-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    // ── XL (48-53GB VRAM, tensor split candidates) ──────────────────
    CatalogModel {
        name: "Llama-3.3-70B-Instruct-Q4_K_M",
        file: "Llama-3.3-70B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf",
        size: "42.5GB",
        description: "Meta Llama 3.3 70B, strong all-around",
        draft: Some("Llama-3.2-1B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen2.5-72B-Instruct-Q4_K_M",
        file: "Qwen2.5-72B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Qwen2.5-72B-Instruct-GGUF/resolve/main/Qwen2.5-72B-Instruct-Q4_K_M.gguf",
        size: "47.4GB",
        description: "Flagship Qwen2.5, great tensor split showcase",
        draft: Some("Qwen2.5-0.5B-Instruct-Q4_K_M"),
        moe: None,
        extra_files: &[],
    },
    // ── XXL (100GB+ VRAM, split GGUF) ─────────────────────────────
    CatalogModel {
        name: "GLM-5-UD-IQ2_XXS",
        file: "GLM-5-UD-IQ2_XXS-00001-of-00006.gguf",
        url: "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00001-of-00006.gguf",
        size: "224GB",
        description: "GLM-5 MoE 300B/24B active, 256 experts top-8, ultra-quantised IQ2_XXS",
        draft: None,
        moe: Some(MoeConfig {
            n_expert: 256,
            n_expert_used: 8,
            min_experts_per_node: 96,
            ranking: &[],
        }),
        extra_files: &[
            ("GLM-5-UD-IQ2_XXS-00002-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00002-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00003-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00003-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00004-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00004-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00005-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00005-of-00006.gguf"),
            ("GLM-5-UD-IQ2_XXS-00006-of-00006.gguf", "https://huggingface.co/unsloth/GLM-5-GGUF/resolve/main/UD-IQ2_XXS/GLM-5-UD-IQ2_XXS-00006-of-00006.gguf"),
        ],
    },
    // ── Draft models ────────────────────────────────────────────────
    CatalogModel {
        name: "Qwen2.5-0.5B-Instruct-Q4_K_M",
        file: "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
        size: "491MB",
        description: "Draft for Qwen2.5 and DeepSeek-R1-Distill models",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Qwen3-0.6B-Q4_K_M",
        file: "Qwen3-0.6B-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_K_M.gguf",
        size: "397MB",
        description: "Draft for Qwen3 models",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Llama-3.2-1B-Instruct-Q4_K_M",
        file: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        size: "760MB",
        description: "Draft for Llama 3.x and Llama 4 models",
        draft: None,
        moe: None,
        extra_files: &[],
    },
    CatalogModel {
        name: "Gemma-3-1B-it-Q4_K_M",
        file: "Gemma-3-1B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q4_K_M.gguf",
        size: "780MB",
        description: "Draft for Gemma 3 models",
        draft: None,
        moe: None,
        extra_files: &[],
    },
];

/// Get the models directory (~/.models/)
pub fn models_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".models")
}

/// Find a catalog model by name (case-insensitive partial match)
/// Parse a size string like "20GB", "4.4GB", "491MB" into GB as f64.
pub fn parse_size_gb(s: &str) -> f64 {
    let s = s.trim();
    if let Some(gb) = s.strip_suffix("GB") {
        gb.trim().parse().unwrap_or(0.0)
    } else if let Some(mb) = s.strip_suffix("MB") {
        mb.trim().parse::<f64>().unwrap_or(0.0) / 1000.0
    } else {
        0.0
    }
}

pub fn find_model(query: &str) -> Option<&'static CatalogModel> {
    let q = query.to_lowercase();
    MODEL_CATALOG
        .iter()
        .find(|m| m.name.to_lowercase() == q)
        .or_else(|| {
            MODEL_CATALOG
                .iter()
                .find(|m| m.name.to_lowercase().contains(&q))
        })
}

/// Download a model to ~/.models/ with resume support.
/// Returns the path to the primary downloaded file.
/// For split GGUFs (extra_files), downloads all parts to the same directory.
pub async fn download_model(model: &CatalogModel) -> Result<PathBuf> {
    let dir = models_dir();
    tokio::fs::create_dir_all(&dir).await?;
    let dest = dir.join(model.file);

    // Collect all files to download: primary + extra splits
    let mut files: Vec<(&str, &str)> = vec![(model.file, model.url)];
    for (f, u) in model.extra_files {
        files.push((f, u));
    }

    let mut all_present = true;
    let mut total_size: u64 = 0;
    for (file, _) in &files {
        let path = dir.join(file);
        let size = tokio::fs::metadata(&path).await.map(|m| m.len()).unwrap_or(0);
        if size < 1_000_000 {
            all_present = false;
            break;
        }
        total_size += size;
    }

    if all_present {
        eprintln!(
            "✅ {} already exists ({:.1}GB, {} file{})",
            model.name,
            total_size as f64 / 1e9,
            files.len(),
            if files.len() > 1 { "s" } else { "" },
        );
        return Ok(dest);
    }

    eprintln!("📥 Downloading {} ({})...", model.name, model.size);
    for (i, (file, url)) in files.iter().enumerate() {
        let path = dir.join(file);
        if path.exists() {
            let size = tokio::fs::metadata(&path).await.map(|m| m.len()).unwrap_or(0);
            if size > 1_000_000 {
                eprintln!("  ✅ {file} already exists ({:.1}GB)", size as f64 / 1e9);
                continue;
            }
        }
        if files.len() > 1 {
            eprintln!("  📥 [{}/{}] {file}...", i + 1, files.len());
        }
        download_with_resume(&path, url).await?;
    }
    eprintln!("✅ Downloaded {} to {}", model.name, dir.display());
    Ok(dest)
}

/// Download any URL to a destination path with resume support.
pub async fn download_url(url: &str, dest: &Path) -> Result<()> {
    download_with_resume(dest, url).await
}

/// Number of parallel connections for large downloads.
const PARALLEL_CHUNKS: usize = 8;

/// Minimum file size to use parallel downloads (100MB).
const PARALLEL_THRESHOLD: u64 = 100_000_000;

/// Download with parallel chunked connections for large files, single-stream for small.
/// Supports resume: each chunk tracks its own progress via marker files.
async fn download_with_resume(dest: &Path, url: &str) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3600))
        .connect_timeout(std::time::Duration::from_secs(30))
        .build()?;

    // Probe file size and Range support with HEAD
    let total_bytes = probe_size(&client, url).await;

    if let Some(total) = total_bytes {
        if total >= PARALLEL_THRESHOLD {
            return download_parallel(dest, url, &client, total).await;
        }
    }

    // Small file or no Content-Length — single stream
    download_single_stream(dest, url, &client).await
}

/// Probe file size using a minimal Range GET request.
/// HEAD doesn't reliably return Content-Length through CDN redirects (e.g. HF's xet-bridge),
/// so we request "bytes=0-0" and parse the Content-Range header for the total size.
async fn probe_size(client: &reqwest::Client, url: &str) -> Option<u64> {
    // Try Range GET first — most reliable through CDNs
    let resp = client.get(url)
        .header("Range", "bytes=0-0")
        .send().await.ok()?;

    if resp.status() == reqwest::StatusCode::PARTIAL_CONTENT {
        // Content-Range: bytes 0-0/396705472
        if let Some(cr) = resp.headers().get("content-range") {
            if let Ok(s) = cr.to_str() {
                if let Some(total) = s.rsplit('/').next().and_then(|s| s.parse::<u64>().ok()) {
                    return Some(total);
                }
            }
        }
    }

    // Fallback: check Content-Length from a normal HEAD
    let resp = client.head(url).send().await.ok()?;
    resp.content_length().filter(|&cl| cl > 0)
}

/// Parallel chunked download: split file into N ranges, download concurrently.
async fn download_parallel(
    dest: &Path,
    url: &str,
    client: &reqwest::Client,
    total_bytes: u64,
) -> Result<()> {
    use tokio_stream::StreamExt;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::sync::Arc;

    let tmp = dest.with_extension("gguf.part");
    let n_chunks = PARALLEL_CHUNKS;
    let chunk_size = total_bytes / n_chunks as u64;

    eprintln!("  ⚡ Parallel download: {:.1}GB in {} chunks",
        total_bytes as f64 / 1e9, n_chunks);

    // Pre-allocate the output file to full size
    {
        let f = tokio::fs::OpenOptions::new()
            .create(true).write(true).open(&tmp).await?;
        f.set_len(total_bytes).await?;
    }

    // Shared progress counter
    let progress = Arc::new(AtomicU64::new(0));
    let start_time = std::time::Instant::now();

    // Each chunk has a marker file: dest.part.chunk-N.done
    let chunk_done = |i: usize| -> PathBuf {
        dest.with_extension(format!("part.chunk-{i}.done"))
    };

    let mut handles = Vec::new();

    for i in 0..n_chunks {
        let start = i as u64 * chunk_size;
        let end = if i == n_chunks - 1 { total_bytes - 1 } else { (i as u64 + 1) * chunk_size - 1 };
        let this_chunk_size = end - start + 1;

        // Skip completed chunks (resume from previous run)
        let marker = chunk_done(i);
        if marker.exists() {
            progress.fetch_add(this_chunk_size, Ordering::Relaxed);
            continue;
        }

        let client = client.clone();
        let url = url.to_string();
        let tmp = tmp.clone();
        let progress = progress.clone();
        let marker = marker.clone();

        let handle = tokio::spawn(async move {
            for attempt in 1..=5 {
                let resp = match client.get(&url)
                    .header("Range", format!("bytes={start}-{end}"))
                    .send().await
                {
                    Ok(r) => r,
                    Err(e) => {
                        eprintln!("  chunk {i}: connection failed (attempt {attempt}): {e}");
                        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                        continue;
                    }
                };

                if resp.status() != reqwest::StatusCode::PARTIAL_CONTENT {
                    eprintln!("  chunk {i}: unexpected status {} (attempt {attempt})", resp.status());
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    continue;
                }

                // Write directly to offset in file using pwrite (no seek contention)
                let file = match std::fs::OpenOptions::new().write(true).open(&tmp) {
                    Ok(f) => f,
                    Err(e) => {
                        eprintln!("  chunk {i}: file open failed: {e}");
                        return Err(anyhow::anyhow!("chunk {i} file open: {e}"));
                    }
                };

                #[cfg(unix)]
                use std::os::unix::fs::FileExt;

                let mut stream = resp.bytes_stream();
                let mut offset = start;

                while let Some(result) = stream.next().await {
                    match result {
                        Ok(chunk) => {
                            #[cfg(unix)]
                            file.write_at(&chunk, offset)?;
                            #[cfg(not(unix))]
                            {
                                use std::io::{Seek, Write};
                                let mut f = &file;
                                f.seek(std::io::SeekFrom::Start(offset))?;
                                f.write_all(&chunk)?;
                            }
                            offset += chunk.len() as u64;
                            progress.fetch_add(chunk.len() as u64, Ordering::Relaxed);
                        }
                        Err(e) => {
                            eprintln!("  chunk {i}: stream error (attempt {attempt}): {e}");
                            break;
                        }
                    }
                }

                if offset == end + 1 {
                    // Chunk complete — write marker
                    let _ = std::fs::write(&marker, b"done");
                    return Ok(());
                }
                // Didn't finish — retry
                tokio::time::sleep(std::time::Duration::from_secs(3)).await;
            }
            Err(anyhow::anyhow!("chunk {i} failed after 5 attempts"))
        });

        handles.push(handle);
    }

    // Progress display loop
    let progress_display = progress.clone();
    let display_handle = tokio::spawn(async move {
        loop {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            let done = progress_display.load(Ordering::Relaxed);
            let elapsed = start_time.elapsed().as_secs_f64();
            let speed = if elapsed > 0.0 { done as f64 / elapsed } else { 0.0 };
            let pct = done as f64 / total_bytes as f64 * 100.0;
            let eta = if speed > 0.0 { (total_bytes - done) as f64 / speed } else { 0.0 };
            eprint!("\r  {:.1}/{:.1}GB ({:.1}%) {:.0}MB/s ETA {:.0}s    ",
                done as f64 / 1e9, total_bytes as f64 / 1e9, pct, speed / 1e6, eta);
            if done >= total_bytes { break; }
        }
    });

    // Wait for all chunks
    let mut all_ok = true;
    for handle in handles {
        match handle.await {
            Ok(Ok(())) => {},
            Ok(Err(e)) => { eprintln!("\n  chunk failed: {e}"); all_ok = false; }
            Err(e) => { eprintln!("\n  chunk panicked: {e}"); all_ok = false; }
        }
    }

    display_handle.abort();
    eprintln!(); // newline after progress

    if !all_ok {
        anyhow::bail!("parallel download failed — some chunks did not complete");
    }

    // Clean up chunk markers
    for i in 0..n_chunks {
        let _ = tokio::fs::remove_file(chunk_done(i)).await;
    }

    // Rename to final destination
    tokio::fs::rename(&tmp, dest).await
        .context("Failed to move downloaded file")?;

    let elapsed = start_time.elapsed().as_secs_f64();
    eprintln!("  ✅ {:.1}GB in {:.0}s ({:.0}MB/s, {} connections)",
        total_bytes as f64 / 1e9, elapsed, total_bytes as f64 / elapsed / 1e6, n_chunks);

    Ok(())
}

/// Single-stream download with resume (for small files or servers without Range).
async fn download_single_stream(
    dest: &Path,
    url: &str,
    client: &reqwest::Client,
) -> Result<()> {
    use tokio_stream::StreamExt;

    let tmp = dest.with_extension("gguf.part");

    for attempt in 1..=5 {
        let existing_bytes = if tmp.exists() {
            tokio::fs::metadata(&tmp).await?.len()
        } else {
            0
        };

        eprintln!(
            "  attempt {attempt}/5{}...",
            if existing_bytes > 0 {
                format!(" (resuming from {:.1}MB)", existing_bytes as f64 / 1e6)
            } else {
                String::new()
            }
        );

        let mut request = client.get(url);
        if existing_bytes > 0 {
            request = request.header("Range", format!("bytes={existing_bytes}-"));
        }

        let response = match request.send().await {
            Ok(r) => r,
            Err(e) => {
                eprintln!("  connection failed: {e}");
                if attempt < 5 {
                    eprintln!("  retrying in 3s...");
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                }
                continue;
            }
        };

        let status = response.status();
        if !status.is_success() && status != reqwest::StatusCode::PARTIAL_CONTENT {
            if status == reqwest::StatusCode::RANGE_NOT_SATISFIABLE {
                let _ = tokio::fs::remove_file(&tmp).await;
                eprintln!("  server rejected resume, starting fresh...");
                continue;
            }
            anyhow::bail!("HTTP {status} downloading {url}");
        }

        let total_bytes = if status == reqwest::StatusCode::PARTIAL_CONTENT {
            response
                .headers()
                .get("content-range")
                .and_then(|v| v.to_str().ok())
                .and_then(|s| s.rsplit('/').next())
                .and_then(|s| s.parse::<u64>().ok())
        } else {
            response.content_length().map(|cl| cl + existing_bytes)
        };

        let mut file = tokio::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&tmp)
            .await
            .context("Failed to open temp file")?;

        let mut stream = response.bytes_stream();
        let mut downloaded = existing_bytes;
        let mut last_progress = std::time::Instant::now();

        print_progress(downloaded, total_bytes);

        loop {
            match stream.next().await {
                Some(Ok(chunk)) => {
                    file.write_all(&chunk)
                        .await
                        .context("Failed to write chunk")?;
                    downloaded += chunk.len() as u64;

                    if last_progress.elapsed() >= std::time::Duration::from_millis(500) {
                        print_progress(downloaded, total_bytes);
                        last_progress = std::time::Instant::now();
                    }
                }
                Some(Err(e)) => {
                    file.flush().await.ok();
                    eprint!("\r");
                    eprintln!(
                        "  download interrupted at {:.1}MB: {e}",
                        downloaded as f64 / 1e6
                    );
                    if attempt < 5 {
                        eprintln!("  retrying in 3s (will resume)...");
                        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    }
                    break;
                }
                None => {
                    file.flush().await?;
                    eprint!("\r");
                    print_progress(downloaded, total_bytes);
                    eprintln!();
                    tokio::fs::rename(&tmp, dest)
                        .await
                        .context("Failed to move downloaded file")?;
                    return Ok(());
                }
            }
        }
    }

    let _ = tokio::fs::remove_file(&tmp).await;
    anyhow::bail!("Download failed after 5 attempts");
}

fn print_progress(downloaded: u64, total: Option<u64>) {
    if let Some(total) = total {
        let pct = (downloaded as f64 / total as f64) * 100.0;
        let downloaded_mb = downloaded as f64 / 1e6;
        let total_mb = total as f64 / 1e6;
        eprint!("\r  {:.1}/{:.1}MB ({:.1}%)", downloaded_mb, total_mb, pct);
    } else {
        eprint!("\r  {:.1}MB", downloaded as f64 / 1e6);
    }
}

/// List available models
pub fn list_models() {
    eprintln!("Available models:");
    eprintln!();
    for m in MODEL_CATALOG {
        let draft_info = if let Some(d) = m.draft {
            format!(" (draft: {})", d)
        } else {
            String::new()
        };
        eprintln!(
            "  {:40} {:>6}  {}{}",
            m.name, m.size, m.description, draft_info
        );
    }
}
